# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Aggression to the Mean
email: aggression-to-the-mean@protonmail.com
description: Using data analytics to understand the fight game. 
baseurl: "/AttM" # the subpath of your site, e.g. /blog
url: "https://aggression-to-the-mean.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AttM_stats
github_username:  aggression-to-the-mean




# fields that were not defaulted
author: AttM
instagram_username: aggressiontothemean
# the below does not work and I am not sure why... Perhaps I need more views! 
# youtube_username: "channel/UC0uVn1nq5HRWLrdMHHJxIsQ"  


# title logo is a new field
title-logo: /images/title-logo.png


# ignore my Rmd files
# ignore vendor as well since it produces the following error :
# Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/2.6.0/gems/jekyll-3.9.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter
exclude: 
 - '*.Rmd'
 - vendor/


# Build settings
# removed minima theme as it is now a regular theme
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
